### ISSUE TITLE
CocoaPods Support for Swift-ogg

### ISSUE THREAD

**Issue by Alenroyfeild** [element-hq/swift-ogg#15]
Problem Description:
Currently, Swift-ogg does not support CocoaPods integration, making it inconvenient for users who prefer to manage dependencies using CocoaPods.

Solution Desired:
I would like to request support for CocoaPods integration for Swift-ogg. This would allow users to easily include Swift-ogg in their projects by adding it to their Podfile.

Alternatives Considered:
As an alternative, users can currently integrate Swift-ogg manually by adding the source files directly to their projects. However, this approach is less convenient and can lead to maintenance issues when updating the library.

Additional Context:
Swift-ogg is a valuable library for handling Ogg Vorbis audio files in Swift projects. Adding CocoaPods support would make it more accessible to a wider range of developers who rely on CocoaPods for dependency management.

**Comment by stefanceriu** [comment]
I'm sorry but we are not considering adding CocoaPod support and probably never will. SPM can be used along side CocoaPods just fine and that should be enough for most installations (we actually do that ourselves in Legacy Element iOS: [SPM](https://github.com/element-hq/element-ios/blob/develop/project.yml#L45) + [CocoaPods](https://github.com/element-hq/element-ios/blob/develop/Podfile))
