### ISSUE TITLE
Undefined symbol: _ogg_ not found for architecture arm64 (M1)

### ISSUE THREAD

**Issue by emretekince** [element-hq/swift-ogg#2]
Can't build the project for iOS Simulator on M1 Apple Silicon

Xcode 14 Beta 2
Screenshot
![Screenshot 2022-07-06 at 15 05 04](https://user-images.githubusercontent.com/5754074/177569441-336d547f-fbe0-40cd-94b9-7d626c9487dc.png)

**Comment by langleyd** [comment]
Hey @emretekince ,
Yea we saw the same just on m1 macs, it should be fixed with https://github.com/vector-im/swift-ogg/pull/3 if you want to try again.

Thanks
